
CREATE TABLE STUDENTS
(
	STUID INT,
	FIRSTNAME VARCHAR(50),
	LASTNAME VARCHAR(50),
	WEBSITE VARCHAR(50),
	CITY VARCHAR(50),
	DIVISION VARCHAR(50)
)

INSERT INTO STUDENTS VALUES
(1011,'KEYUR','PATEL','TECHONTHENET.COM','RAJKOT','II-BCX'),
(1022,'HARDIK','SHAH','DIGIMINECRAFT.COM','AHMEDABAD','I-BCY'),
(1033,'KAJAL','TRIVEDI','BIGACTIVITIES.COM','BARODA','IV-DCX'),
(1044,'BHOOMI','GAJERA','CHECKYOURMATH.COM','AHMEDABAD','III-DCW'),
(1055,'HARMIT','MITAL',NULL,'RAJKOT','II-BCY'),
(1066,'ASHOK','JANI',NULL,'BARODA','II-BCZ')


--SELECT * FROM STUDENTS
--SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE 'K%'
--SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE'_____'
--SELECT FIRSTNAME,LASTNAME FROM STUDENTS WHERE CITY LIKE '_____%A'
--SELECT * FROM STUDENTS WHERE LASTNAME LIKE '%TEL'
--SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE 'HA%T'
--SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE 'K_Y%'
--SELECT FIRSTNAME FROM STUDENTS WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '_____'
--SELECT * FROM STUDENTS WHERE LASTNAME LIKE '%JER%'
--SELECT * FROM STUDENTS WHERE CITY LIKE '[R,B]%'
--SELECT FIRSTNAME FROM STUDENTS WHERE WEBSITE IS NOT NULL
--SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE '[A-H]%'
--SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE '_[A,E,I,O,U]%'
--SELECT FIRSTNAME FROM STUDENTS WHERE CITY LIKE '%ROD%'
--SELECT FIRSTNAME,LASTNAME FROM STUDENTS WHERE WEBSITE LIKE 'BI%'
--SELECT CITY FROM STUDENTS WHERE LASTNAME LIKE '______'
--SELECT * FROM STUDENTS WHERE CITY LIKE '_____' AND CITY NOT LIKE 'BA%'
--SELECT * FROM STUDENTS WHERE DIVISION LIKE 'II%'
--SELECT FIRSTNAME FROM STUDENTS WHERE DIVISION LIKE '%BC%'
--SELECT STUID,CITY FROM STUDENTS WHERE DIVISION LIKE '______' AND WEBSITE IS NOT NULL
--SELECT * FROM STUDENTS WHERE FIRSTNAME NOT LIKE '__[A,E,I,O,U]%'
--SELECT * FROM STUDENTS WHERE FIRSTNAME NOT LIKE '^[A-H]'
--SELECT * FROM STUDENTS WHERE FIRSTNAME LIKE '^[A-H]'