CREATE TABLE COMPUTER(
	ROLLNO INT,
	NAME VARCHAR(50)
)

CREATE TABLE ELECTRICAL(
	ROLLNO INT,
	NAME VARCHAR(50)
)

INSERT INTO COMPUTER VALUES
(101,'AJAY'),
(102,'HARESH'),
(103,'MANISH')

INSERT INTO ELECTRICAL VALUES
(105,'AJAY'),
(107,'MAHESH'),
(115,'MANISH')


--1
SELECT NAME FROM COMPUTER 
UNION
SELECT NAME FROM ELECTRICAL 


--2
SELECT NAME FROM COMPUTER 
UNION ALL
SELECT NAME FROM ELECTRICAL 

--3
SELECT NAME FROM COMPUTER 
INTERSECT
SELECT NAME FROM ELECTRICAL  

--4
SELECT NAME FROM COMPUTER 
EXCEPT
SELECT NAME FROM ELECTRICAL 

--5
SELECT NAME FROM ELECTRICAL 
EXCEPT
SELECT NAME FROM COMPUTER

--6
SELECT * FROM COMPUTER 
UNION
SELECT * FROM ELECTRICAL

--7
SELECT * FROM COMPUTER 
INTERSECT
SELECT * FROM ELECTRICAL

--------------------------------------------------------
CREATE TABLE CRICKET(
	NAME VARCHAR(50),
	CITY VARCHAR(50),
	AGE INT
)

INSERT INTO CRICKET VALUES
('SACHIN TENDULKAR','MUMBAI',30),
('RAHUL DRAVID','BOMBAY',35),
('M.S.DHONI','JARKHAND',31),
('SURESH RAINA','GUJRAT',30)

--1
SELECT * INTO WORD_CUP FROM CRICKET

--2
SELECT NAME,CITY INTO T20 FROM CRICKET  WHERE 1=0

--3
SELECT * INTO IPL FROM CRICKET WHERE 1=0

--4
INSERT INTO IPL SELECT * FROM CRICKET WHERE NAME LIKE '_A_____%'

--5
DELETE FROM IPL

--6
DELETE FROM CRICKET WHERE CITY='JARKHAND'

--7
SP_RENAME 'IPL','IPL2018'

--8
DROP TABLE T20