CREATE TABLE STUDENT(
	RNO INT,
	NAME VARCHAR(50),
	CITY VARCHAR(50),
	DID INT
)

INSERT INTO STUDENT VALUES
(101,'RAJU','RAJKOT',10),
(102,'AMIT','AHMEDABAD',20),
(103,'SANJAY','BARODA',40),
(104,'NEHA','RAJKOT',20),
(105,'MEERA','AHMEDABAD',30),
(106,'MAHESH','BARODA',10)

CREATE TABLE ACADAMIC(
	RNO INT,
	SPI DECIMAL(4,2),
	BKLOG INT
)

INSERT INTO ACADAMIC VALUES
(101,8.8,0),
(102,9.2,2),
(103,7.6,1),
(104,8.2,4),
(105,7.0,2),
(106,8.9,3)

CREATE TABLE DEPARTMENT(
	DID INT,
	DNAME VARCHAR(50)
)

INSERT INTO DEPARTMENT VALUES
(10,'COMPUTER'),
(20,'ELECTRICAL'),
(30,'MECHANICAL'),
(40,'CIVIL')


--1
SELECT RNO, NAME, CITY
FROM STUDENT
WHERE DID= (SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER');

--2
SELECT NAME
FROM STUDENT
WHERE RNO IN (SELECT RNO FROM ACADAMIC WHERE SPI>8);

--3
SELECT RNO, NAME, CITY
FROM STUDENT
WHERE CITY='RAJKOT' AND DID=(SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER');

--4
SELECT COUNT(*)
FROM STUDENT
WHERE DID=(SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL');

--5
SELECT NAME
FROM STUDENT
WHERE RNO=(SELECT RNO FROM ACADAMIC WHERE SPI=( SELECT MAX(SPI)FROM ACADAMIC) );

--6
SELECT *
FROM STUDENT
WHERE RNO IN (SELECT RNO FROM ACADAMIC WHERE BKLOG>1);

--7
SELECT NAME
FROM STUDENT
WHERE RNO=(SELECT RNO
FROM ACADAMIC
WHERE SPI=(SELECT MAX(SPI)
FROM ACADAMIC WHERE SPI< (SELECT MAX(SPI) FROM ACADAMIC) ) );

--8
SELECT NAME
FROM STUDENT
WHERE DID IN (SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER' OR DNAME='MECHANICAL');

--9
SELECT NAME
FROM STUDENT
WHERE DID=(SELECT DID FROM STUDENT WHERE RNO=102);

--10
SELECT NAME
FROM STUDENT
WHERE RNO IN (SELECT RNO FROM ACADAMIC WHERE SPI>9) 
AND 
DID= (SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL');