CREATE TABLE STUDENT_VIEW(
	RNO INT,
	NAME VARCHAR(50),
	BRANCH VARCHAR(50),
	SPI DECIMAL(4,2),
	BKLOG INT
)
INSERT INTO STUDENT_VIEW VALUES
(101,'RAJU','CE',8.80,0),
(102,'AMIT','CE',2.20,3),
(103,'SANJAY','ME',1.50,6),
(104,'NEHA','EC',7.65,1),
(104,'MEERA','EC',5.52,2),
(105,'MAHESH','EC',4.50,3)

--1
CREATE VIEW PERSONAL
AS
SELECT *
FROM STUDENT_VIEW
--SELECT * FROM PERSONAL


--2
CREATE VIEW STUDENT_DETAILS
AS
SELECT NAME,BRANCH,SPI
FROM STUDENT_VIEW
--SELECT * FROM STUDENT_DETAILS

--3
CREATE VIEW ACADAMIC
AS
SELECT RNO,NAME,BRANCH
FROM STUDENT_VIEW
--SELECT * FROM ACADAMIC

--4
CREATE VIEW STUDENT_DATA 
AS
SELECT * 
FROM STUDENT_VIEW
WHERE BKLOG>2
--SELECT * FROM STUDENT_DATA

--5
CREATE VIEW STUDENT_PATTERN 
AS
SELECT RNO,NAME,BRANCH
FROM STUDENT_VIEW
WHERE NAME LIKE '____'
--SELECT * FROM STUDENT_PATTERN

--6
INSERT INTO ACADAMIC VALUES(107,'MEET','ME')
--OR
INSERT INTO ACADAMIC SELECT 107,'MEET','ME'
--SELECT * FROM ACADAMIC

--7
UPDATE STUDENT_DETAILS SET BRANCH='ME' WHERE NAME='AMIT'
--SELECT * FROM STUDENT_DETAILS

--8
DELETE FROM ACADAMIC WHERE RNO=104
--SELECT * FROM ACADAMIC

--9
CREATE VIEW STUDENT_INFORMATION 
AS
SELECT *
FROM STUDENT_VIEW
WHERE SPI>9.5
--SELECT * FROM STUDENT_INFORMATION

--10
CREATE VIEW BKLOG
AS
SELECT *
FROM STUDENT_VIEW
WHERE BKLOG=0
--SELECT * FROM BKLOG



