--SELECT * FROM DEPOSIT
--SELECT * FROM BORROW
--SELECT * FROM CUSTOMERS
--SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT
--SELECT LOANNO,AMOUNT FROM BORROW
--SELECT * FROM BORROW WHERE BNAME='ANDHERI'
--SELECT ACTNO,AMOUNT FROM DEPOSIT WHERE ACTNO=106
--SELECT * FROM BORROW WHERE AMOUNT>5000
--SELECT CNAME FROM DEPOSIT WHERE ADATE>'1996-12-1'
--SELECT CNAME FROM DEPOSIT WHERE ACTNO<105
--SELECT CNAME FROM CUSTOMERS WHERE CITY='NAGPUR' OR CITY='DEHI'
--SELECT CNAME FROM CUSTOMERS WHERE CITY IN('NAGPUR','DEHI')
--SELECT CNAME,BNAME FROM BORROW WHERE AMOUNT>=4000 AND AMOUNT<=8000
--SELECT CNAME FROM BORROW WHERE AMOUNT>=3000 AND AMOUNT<=8000
--SELECT * FROM BORROW WHERE AMOUNT BETWEEN 3000 AND 8000
--SELECT * FROM DEPOSIT WHERE BNAME<>'ANDHERI'
--SELECT TOP 30 PERCENT * FROM DEPOSIT
--SELECT TOP 5 * FROM DEPOSIT
--SELECT DISTINCT CITY FROM BRANCH
--SELECT DISTINCT * FROM BORROW
--SELECT * FROM DEPOSIT ORDER BY CNAME
--SELECT * FROM DEPOSIT ORDER BY CNAME DESC
--SELECT * FROM DEPOSIT ORDER BY CNAME,BNAME
--SELECT ACTNO AS ACOUNTNUMBER,CNAME [CUSTOMER NAME],AMOUNT amount FROM DEPOSIT 
--SELECT CNAME FROM BORROW WHERE AMOUNT IS NULL
--SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT WHERE BNAME IN('AJNI','KAROLBAGH','M.G.ROAD') AND ACTNO<104
--SELECT TOP 5 * FROM CUSTOMERS
--SELECT TOP 3 * FROM DEPOSIT WHERE AMOUNT>1000
--SELECT TOP 5 LOANNO,CNAME FROM BORROW WHERE BNAME<>'ANDHERI'
--SELECT DISTINCT CITY FROM CUSTOMERS
--SELECT DISTINCT BNAME FROM BRANCH
--SELECT * FROM CUSTOMERS ORDER BY CITY
--SELECT * FROM DEPOSIT ORDER BY AMOUNT DESC
--SELECT * FROM CUSTOMERS ORDER BY CITY DESC
--SELECT DISTINCT CNAME AS UNI_Borrowers FROM BORROW 







